framework:
  messenger:
    transports:
      async: 'doctrine://default?queue_name=async'

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      OpenDemat\Core\Mailer\Message\TemplatedMailMessage: async
