open_demat_admin:
  organization:
    name: '%env(default::ORGANIZATION_NAME)%'
    logo: '%env(default:organization_logo_default:ORGANIZATION_LOGO)%'
  theme:
    primary_color: '%env(default::THEME_PRIMARY_COLOR)%'
    primary_dark_color: '%env(default::THEME_PRIMARY_DARK_COLOR)%'
  cas:
    base_url: '%env(default::CAS_BASE_URL)%'
    logout_url: '%env(default::CAS_LOGOUT_URL)%'
    host: '%env(default::CAS_HOST)%'
    port: '%env(default::CAS_PORT)%'
    path: '%env(default::CAS_PATH)%'
    login_target: '%env(default::CAS_LOGIN_TARGET)%'
    gateway: '%env(default::CAS_GATEWAY)%'
  saml2:
    enabled: '%env(default::SAML2_ENABLED)%'
    identifier_attribute: '%env(default::SAML2_IDENTIFIER_ATTRIBUTE)%'
    email_attribute: '%env(default::SAML2_EMAIL_ATTRIBUTE)%'
    first_name_attribute: '%env(default::SAML2_FIRST_NAME_ATTRIBUTE)%'
    last_name_attribute: '%env(default::SAML2_LAST_NAME_ATTRIBUTE)%'
    default_email_domain: '%env(default::SAML2_DEFAULT_EMAIL_DOMAIN)%'
    auto_create_user: '%env(default::SAML2_AUTO_CREATE_USER)%'
    login_url: '%env(default::SAML2_LOGIN_URL)%'
  s3:
    endpoint: '%env(default::S3_ENDPOINT)%'
    region: '%env(default::S3_REGION)%'
    bucket: '%env(default::S3_BUCKET)%'
    use_path_style: '%env(default::S3_USE_PATH_STYLE)%'
    access_key: '%env(default::S3_ACCESS_KEY)%'
    secret_key: '%env(default::S3_SECRET_KEY)%'
