security:
  #enable_authenticator_manager: true

  role_hierarchy:
    ROLE_ADMIN:
      - ROLE_USER
      - ROLE_ADMIN

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: OpenDemat\Core\Entity\User
        property: username

    in_memory:
      memory:
        users:
          __NO_USER__:
            password:
            roles: ROLE_ANON

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - OpenDemat\Core\Security\LocalAdminAuthenticator
        - OpenDemat\Core\Security\LdapAuthenticator
        - OpenDemat\Core\Security\SAML2Authenticator
        - OpenDemat\Core\Security\CasAuthenticator
      entry_point: OpenDemat\Core\Security\LoginChoiceEntryPoint
      logout:
        path: /logout

  access_control:
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/saml2, roles: PUBLIC_ACCESS }
    - { path: ^/cas/login, roles: PUBLIC_ACCESS }
    - { path: ^/cas/force, roles: PUBLIC_ACCESS }
    - { path: ^/llogout, roles: PUBLIC_ACCESS }

    - { path: ^/profile, roles: ROLE_USER }

    # Admin Open Demat
    - { attributes: { '_route': '^open_demat_admin_' }, roles: ROLE_ADMIN }
    - { attributes: { '_route': '^admin$' }, roles: ROLE_ADMIN }

    # Example bundle
    - { attributes: { '_route': '^open_demat_example_admin_' }, roles: ROLE_ADMIN }
    - { attributes: { '_route': '^open_demat_example_' }, roles: ROLE_USER }

    # CSST - règles spécifiques avant les règles globales
    - { attributes: { '_route': '^csst_admin_' }, roles: ROLE_CSST_POWERUSER }

    # Création d'une observation accessible à tous les utilisateurs connectés
    - { attributes: { '_route': '^csst_observation_new$' }, roles: ROLE_USER }

    # Toutes les autres routes observation restent réservées aux rôles CSST
    - { attributes: { '_route': '^csst_observation_' }, roles: [ROLE_CSST_SHS, ROLE_CSST_AP, ROLE_CSST_F3SCT] }

    # CSST global
    - { attributes: { '_route': '^csst_' }, roles: ROLE_USER }

    # Courriers
    - { attributes: { '_route': '^courriers_' }, roles: ROLE_COURRIERS_OPERATEUR }

    # Véhicules
    - { attributes: { '_route': '^vehicules_admin_' }, roles: ROLE_VEHICULES_POWERUSER }
    - { attributes: { '_route': '^vehicules_' }, roles: ROLE_USER }
