<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260601082919 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add static documents for reusable S3-backed assets.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE static_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, scope VARCHAR(80) NOT NULL, label VARCHAR(180) NOT NULL, active BOOLEAN NOT NULL, disposition VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C6F1FA4AC33F7837 ON static_document (document_id)');
        $this->addSql('CREATE INDEX idx_static_document_scope ON static_document (scope)');
        $this->addSql('CREATE INDEX idx_static_document_active ON static_document (active)');
        $this->addSql('CREATE UNIQUE INDEX uniq_static_document_code ON static_document (code)');
        $this->addSql('ALTER TABLE static_document ADD CONSTRAINT FK_C6F1FA4AC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE static_document DROP CONSTRAINT FK_C6F1FA4AC33F7837');
        $this->addSql('DROP TABLE static_document');
    }
}
