<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261001170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les sous-profils utilisateur par bundle et la mise en silencieux des notifications de suivi';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_bundle_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, bundle_key VARCHAR(50) NOT NULL, notifications_muted BOOLEAN DEFAULT FALSE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_USER_BUNDLE_PROFILE_USER ON user_bundle_profile (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_bundle_profile ON user_bundle_profile (user_id, bundle_key)');
        $this->addSql('ALTER TABLE user_bundle_profile ADD CONSTRAINT FK_USER_BUNDLE_PROFILE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_bundle_profile');
    }
}
