<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261001180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Conserve une copie des notifications dans la boîte de messages utilisateur';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE inbox_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, bundle_key VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_inbox_user_date ON inbox_message (user_id, created_at, id)');
        $this->addSql('ALTER TABLE inbox_message ADD CONSTRAINT fk_inbox_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN inbox_message.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN inbox_message.read_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inbox_message');
    }
}
