<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260126101848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) DEFAULT NULL, category VARCHAR(50) DEFAULT NULL, is_pinned BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, document_id UUID NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38E46E76B03A8386 ON user_document (created_by_id)');
        $this->addSql('CREATE INDEX idx_user_document_user ON user_document (user_id)');
        $this->addSql('CREATE INDEX idx_user_document_document ON user_document (document_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_document_user_doc ON user_document (user_id, document_id)');
        $this->addSql('ALTER TABLE user_document ADD CONSTRAINT FK_38E46E76A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_document ADD CONSTRAINT FK_38E46E76C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_document ADD CONSTRAINT FK_38E46E76B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA f3sct');
        $this->addSql('ALTER TABLE user_document DROP CONSTRAINT FK_38E46E76A76ED395');
        $this->addSql('ALTER TABLE user_document DROP CONSTRAINT FK_38E46E76C33F7837');
        $this->addSql('ALTER TABLE user_document DROP CONSTRAINT FK_38E46E76B03A8386');
        $this->addSql('DROP TABLE user_document');
    }
}
