<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114134504 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE process_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, process_name VARCHAR(50) NOT NULL, case_type VARCHAR(50) NOT NULL, case_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id UUID NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D714FAB3C33F7837 ON process_attachment (document_id)');
        $this->addSql('CREATE INDEX IDX_D714FAB3B03A8386 ON process_attachment (created_by_id)');
        $this->addSql('CREATE INDEX idx_pa_case ON process_attachment (process_name, case_type, case_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pa_case_doc ON process_attachment (process_name, case_type, case_id, document_id)');
        $this->addSql('ALTER TABLE process_attachment ADD CONSTRAINT FK_D714FAB3C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE process_attachment ADD CONSTRAINT FK_D714FAB3B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA f3sct');
        $this->addSql('ALTER TABLE process_attachment DROP CONSTRAINT FK_D714FAB3C33F7837');
        $this->addSql('ALTER TABLE process_attachment DROP CONSTRAINT FK_D714FAB3B03A8386');
        $this->addSql('DROP TABLE process_attachment');
    }
}
