<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410080436 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create persisted role registry table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(190) NOT NULL, module_key VARCHAR(100) DEFAULT NULL, children JSON NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_role_code ON role (code)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE role');
    }
}
