ServerRoot "/usr/local/apache2"
Listen 8081
ServerName shib-dev.localhost

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule headers_module modules/mod_headers.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so

User daemon
Group daemon

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common

ProxyPreserveHost On
RequestHeader set EPPN "jane.doe@example.org"
RequestHeader set MAIL "jane.doe@example.org"
RequestHeader set GIVENNAME "Jane"
RequestHeader set SN "Doe"
RequestHeader set REMOTE-USER "jane.doe@example.org"

ProxyPass / http://127.0.0.1:8001/
ProxyPassReverse / http://127.0.0.1:8001/
