[program:open-demat-mailer]
command=/usr/bin/php /var/www/open-demat/bin/console messenger:consume async --time-limit=3600 --memory-limit=256M --sleep=2
directory=/var/www/open-demat
user=deploy
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=20
killasgroup=true
stopasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/open-demat-mailer.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=APP_ENV="prod",APP_DEBUG="0"
