ServerName shib.localhost

<VirtualHost *:80>
    ServerName shib.localhost

    ProxyPreserveHost On
    ProxyPass /Shibboleth.sso !
    ProxyPass / http://host.docker.internal:8001/
    ProxyPassReverse / http://host.docker.internal:8001/

    <Location />
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        Require valid-user

        RequestHeader set EPPN "%{eppn}e" env=eppn
        RequestHeader set MAIL "%{mail}e" env=mail
        RequestHeader set GIVENNAME "%{givenName}e" env=givenName
        RequestHeader set SN "%{sn}e" env=sn
        RequestHeader set REMOTE-USER "%{REMOTE_USER}e" env=REMOTE_USER
    </Location>
</VirtualHost>
